[nfs]
172.31.16.68 ansible_ssh_user='ec2-user'

[webservers]
172.31.23.118 ansible_ssh_user='ec2-user'
172.31.31.171 ansible_ssh_user='ec2-user'

[db]
172.31.20.33 ansible_ssh_user='ec2-user' 

[lb]
172.31.25.177 ansible_ssh_user='ubuntu'
