pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'tag', defaultValue: 'all',  description: 'Tags to run the ansible playbook against')
    }
    environment {
      branch = 'feature/jenkinspipeline-stages'
    }
    stages {
     stage('Clone repo') {
      steps {
        git(branch: branch, url: 'https://github.com/Damdev-95/ansible-config-mgt.git')
      }
     }
     
     stage('Update ansible.cfg') {
      steps {
       sh "export ANSIBLE_CONFIG=${WORKSPACE}/deploy/ansible.cfg"
      }
     }
     
     stage('Run playbook') {
      steps {
        ansiblePlaybook(credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yaml')
      }
     }
  } 
     
            
     
      
